// <auto-generated />
namespace WebApplication5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ForAttendenceManagement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForAttendenceManagement));
        
        string IMigrationMetadata.Id
        {
            get { return "202002172058526_ For Attendence Management"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
